import type { KeywordValueMapping, PromptTemplateOption } from './types';

export const STORAGE_KEY = 'project-passport-state-v1';
export const THEME_STORAGE_KEY = 'project-passport-theme-v1';
export const AI_MODEL_STORAGE_KEY = 'project-passport-ai-model-v1';

export const PROJECT_PROMPT_TEMPLATE_OPTIONS: PromptTemplateOption[] = [
  {
    id: 'mvp',
    label: 'Build MVP',
    description: 'Create the first functional version from current passport data.',
  },
  {
    id: 'feature',
    label: 'Add Feature',
    description: 'Implement a new capability on top of the existing product.',
  },
  {
    id: 'bugfix',
    label: 'Fix Bug',
    description: 'Diagnose and resolve an issue while minimizing regressions.',
  },
  {
    id: 'refactor',
    label: 'Refactor',
    description: 'Improve internal code quality without changing behavior.',
  },
];

export const LEAD_PROMPT_TEMPLATE_OPTIONS: PromptTemplateOption[] = [
  {
    id: 'lead-qualification',
    label: 'Qualify Lead',
    description: 'Assess lead fit, urgency, and delivery risks based on current context.',
  },
  {
    id: 'lead-discovery',
    label: 'Discovery Questions',
    description: 'Generate focused questions to clarify scope, constraints, and expectations.',
  },
  {
    id: 'lead-proposal',
    label: 'Prepare Proposal',
    description: 'Create proposal-ready structure: scope, assumptions, estimate framing, and next step.',
  },
  {
    id: 'lead-followup',
    label: 'Follow-up Message',
    description: 'Draft a concise manager-facing follow-up message with concrete next actions.',
  },
];

export const PROMPT_TEMPLATE_OPTIONS: PromptTemplateOption[] = [
  ...PROJECT_PROMPT_TEMPLATE_OPTIONS,
  ...LEAD_PROMPT_TEMPLATE_OPTIONS,
];

export const PROMPT_TEMPLATE_TASK_FOCUS: Record<string, string> = {
  mvp: 'Build an MVP implementation plan and execute it in small, verifiable steps.',
  feature: 'Design and implement the requested feature with tests and backward compatibility.',
  bugfix: 'Identify root cause, apply minimal safe fix, and add regression coverage.',
  refactor: 'Refactor structure for maintainability and keep runtime behavior unchanged.',
  'lead-qualification': 'Assess whether this lead is qualified, actionable, and worth prioritizing now.',
  'lead-discovery': 'Produce precise discovery questions that reduce ambiguity before estimation.',
  'lead-proposal': 'Prepare a proposal-oriented outline with assumptions, scope framing, and likely delivery plan.',
  'lead-followup': 'Draft a practical follow-up note that drives the lead to the next concrete step.',
};

export const STACK_DEPENDENT_FIELD_IDS = ['cms', 'database', 'storage', 'authStrategy'] as const;

export const CONVERTER_LABEL_MAPPINGS: Array<{ fieldId: string; labels: string[] }> = [
  { fieldId: 'projectName', labels: ['project name', 'project', 'name', 'product name'] },
  { fieldId: 'passportTemplate', labels: ['passport template', 'template'] },
  { fieldId: 'client', labels: ['client', 'customer'] },
  { fieldId: 'department', labels: ['department', 'team', 'business unit'] },
  { fieldId: 'designTool', labels: ['design tool', 'ui tool', 'figma', 'lovable'] },
  { fieldId: 'designToolUrl', labels: ['design tool link', 'figma link', 'lovable link', 'design url'] },
  { fieldId: 'status', labels: ['status'] },
  { fieldId: 'projectType', labels: ['project type', 'type'] },
  { fieldId: 'priority', labels: ['priority'] },
  { fieldId: 'startedAt', labels: ['started at', 'start date', 'kickoff date'] },
  { fieldId: 'businessGoal', labels: ['business goal', 'goal', 'objective'] },
  { fieldId: 'scopeIn', labels: ['scope in', 'in scope', 'scope'] },
  { fieldId: 'scopeOut', labels: ['scope out', 'out of scope', 'excluded scope'] },
  { fieldId: 'currentStage', labels: ['current stage', 'stage'] },
  { fieldId: 'definitionOfDone', labels: ['definition of done', 'dod', 'done criteria'] },
  { fieldId: 'acceptanceCriteria', labels: ['acceptance criteria', 'acceptance'] },
  { fieldId: 'testAssignmentTitle', labels: ['test assignment title', 'assignment title', 'task title'] },
  { fieldId: 'testAssignmentSourceUrl', labels: ['test assignment url', 'brief url', 'source url', 'task link'] },
  { fieldId: 'testAssignmentStatus', labels: ['assignment status', 'test assignment status'] },
  { fieldId: 'testAssignmentEstimate', labels: ['estimated effort', 'time estimate', 'estimate'] },
  {
    fieldId: 'testAssignmentSubmissionFormat',
    labels: ['submission format', 'delivery format', 'submission type'],
  },
  {
    fieldId: 'testAssignmentDeliverables',
    labels: ['deliverables', 'expected deliverables', 'required artifacts'],
  },
  {
    fieldId: 'testAssignmentEvaluationCriteria',
    labels: ['evaluation criteria', 'grading criteria', 'assessment criteria'],
  },
  { fieldId: 'testAssignmentConstraints', labels: ['constraints', 'limitations', 'notes'] },
  { fieldId: 'leadName', labels: ['lead name', 'opportunity name', 'request name'] },
  { fieldId: 'leadStatus', labels: ['lead status'] },
  { fieldId: 'leadSource', labels: ['lead source'] },
  { fieldId: 'leadContactPerson', labels: ['contact person', 'contact name'] },
  { fieldId: 'communicationChannel', labels: ['communication channel', 'contact channel', 'contact', 'email', 'phone', 'telegram'] },
  { fieldId: 'communicatorPeople', labels: ['communicator', 'who communicates', 'communication person', 'account manager'] },
  { fieldId: 'responsiblePeople', labels: ['responsible', 'responsible person', 'lead owner', 'owner', 'manager'] },
  { fieldId: 'leadSummary', labels: ['request summary', 'summary', 'brief', 'lead description', 'opportunity description'] },
  { fieldId: 'leadBudget', labels: ['budget', 'budget range'] },
  { fieldId: 'leadQualificationNotes', labels: ['qualification notes'] },
  { fieldId: 'leadNextStep', labels: ['next step', 'next action'] },
  { fieldId: 'leadLossReason', labels: ['loss reason', 'reason lost'] },
  { fieldId: 'mainStack', labels: ['main stack', 'stack'] },
  { fieldId: 'secondaryStack', labels: ['secondary stack', 'libraries', 'dependencies'] },
  { fieldId: 'platform', labels: ['platform'] },
  { fieldId: 'hostingDeployment', labels: ['hosting', 'deployment', 'hosting deployment'] },
  { fieldId: 'database', labels: ['database', 'db'] },
  { fieldId: 'cms', labels: ['cms'] },
  { fieldId: 'authStrategy', labels: ['auth', 'authentication', 'auth strategy'] },
  { fieldId: 'storage', labels: ['storage'] },
  { fieldId: 'apiType', labels: ['api type'] },
  { fieldId: 'integrations', labels: ['integrations'] },
  { fieldId: 'repositoryUrl', labels: ['repository', 'repo', 'git'] },
  { fieldId: 'docsUrl', labels: ['docs', 'documentation'] },
  { fieldId: 'stagingUrl', labels: ['staging', 'preview'] },
  { fieldId: 'productionUrl', labels: ['production', 'prod'] },
  { fieldId: 'adminUrl', labels: ['admin'] },
  { fieldId: 'apiBaseUrl', labels: ['api base', 'api url', 'base api', 'api endpoint'] },
  { fieldId: 'runInstallCommand', labels: ['install command'] },
  { fieldId: 'runStartCommand', labels: ['start command', 'run command'] },
  { fieldId: 'runTestCommand', labels: ['test command'] },
  { fieldId: 'runBuildCommand', labels: ['build command'] },
  { fieldId: 'secretStorageReference', labels: ['secrets', 'secret storage'] },
  { fieldId: 'vaultLink', labels: ['vault', 'vault link'] },
  { fieldId: 'accessNotes', labels: ['access notes', 'access'] },
  { fieldId: 'wpType', labels: ['wordpress type', 'wp type'] },
  { fieldId: 'wpThemeType', labels: ['theme type'] },
  { fieldId: 'wpPageBuilder', labels: ['page builder'] },
  { fieldId: 'wpMultilangPlugin', labels: ['multilang plugin', 'multilang'] },
  { fieldId: 'wpSeoPlugin', labels: ['seo plugin'] },
  { fieldId: 'wpAdminUrl', labels: ['wp-admin', 'wp admin'] },
];

export const CONVERTER_SELECT_MAPPINGS: Record<string, KeywordValueMapping[]> = {
  passportTemplate: [
    { value: 'Test Assignment', keywords: ['test assignment', 'technical assignment', 'coding challenge'] },
    { value: 'Standard', keywords: ['standard', 'default template'] },
  ],
  department: [
    { value: 'Development', keywords: ['development', 'engineering', 'dev'] },
    { value: 'UI/UX', keywords: ['ui', 'ux', 'design', 'ui/ux'] },
  ],
  designTool: [
    { value: 'Figma', keywords: ['figma'] },
    { value: 'Lovable', keywords: ['lovable'] },
    { value: 'Other', keywords: ['other'] },
  ],
  status: [
    { value: 'In Progress', keywords: ['in progress', 'active development', 'implement'] },
    { value: 'Planning', keywords: ['planning', 'plan'] },
    { value: 'Discovery', keywords: ['discovery', 'research'] },
    { value: 'QA', keywords: ['qa', 'testing', 'test'] },
    { value: 'Blocked', keywords: ['blocked', 'blocker'] },
    { value: 'On Hold', keywords: ['on hold', 'paused'] },
    { value: 'Done', keywords: ['done', 'completed', 'released'] },
  ],
  projectType: [
    { value: 'Test Assignment', keywords: ['test assignment', 'technical assignment', 'coding challenge'] },
    { value: 'E-commerce', keywords: ['e-commerce', 'ecommerce', 'shop', 'store', 'woocommerce'] },
    { value: 'Mobile Product', keywords: ['mobile', 'ios', 'android', 'app store', 'play store'] },
    { value: 'Desktop Product', keywords: ['desktop', 'electron', 'installer'] },
    { value: 'Full-stack System', keywords: ['full-stack', 'full stack', 'backend and frontend'] },
    { value: 'SaaS Product', keywords: ['saas', 'subscription', 'b2b service'] },
  ],
  priority: [
    { value: 'Critical', keywords: ['critical', 'urgent'] },
    { value: 'High', keywords: ['high'] },
    { value: 'Medium', keywords: ['medium'] },
    { value: 'Low', keywords: ['low'] },
  ],
  mainStack: [
    { value: 'React Native', keywords: ['react native', 'expo', 'ios', 'android'] },
    { value: 'Next.js', keywords: ['next.js', 'nextjs', 'app router'] },
    { value: 'WordPress', keywords: ['wordpress', 'woocommerce', 'wp-admin', 'acf', 'elementor'] },
    { value: 'Electron', keywords: ['electron', 'ipc', 'tray', 'desktop app'] },
    { value: 'React', keywords: ['react', 'vite', 'spa'] },
    { value: 'Generic Full-stack', keywords: ['full stack', 'backend', 'frontend', 'api server'] },
  ],
  platform: [
    { value: 'Cross-platform', keywords: ['cross-platform', 'cross platform', 'ios and android and web'] },
    { value: 'Mobile', keywords: ['mobile', 'ios', 'android'] },
    { value: 'Desktop', keywords: ['desktop', 'electron', 'windows', 'macos'] },
    { value: 'Web', keywords: ['web', 'browser', 'site'] },
  ],
  hostingDeployment: [
    { value: 'Vercel', keywords: ['vercel', 'vercel.app'] },
    { value: 'Netlify', keywords: ['netlify', 'netlify.app'] },
    { value: 'cPanel', keywords: ['cpanel'] },
    { value: 'Shared Hosting', keywords: ['shared hosting'] },
    { value: 'VPS', keywords: ['vps', 'droplet', 'ssh'] },
    { value: 'AWS', keywords: ['aws', 'ec2', 's3', 'cloudfront'] },
    { value: 'Firebase', keywords: ['firebase'] },
    { value: 'Render', keywords: ['render.com', 'render'] },
    { value: 'Railway', keywords: ['railway'] },
    { value: 'Expo EAS', keywords: ['expo eas', 'eas build'] },
    { value: 'App Store / Play Store', keywords: ['app store', 'play store'] },
    { value: 'Desktop Distribution', keywords: ['desktop distribution', 'dmg', 'msi', 'appimage'] },
  ],
  currentStage: [
    { value: 'Discovery', keywords: ['discovery', 'research'] },
    { value: 'Planning', keywords: ['planning', 'plan'] },
    { value: 'Implementation', keywords: ['implementation', 'develop'] },
    { value: 'Testing', keywords: ['testing', 'qa', 'test'] },
    { value: 'Release', keywords: ['release'] },
    { value: 'Maintenance', keywords: ['maintenance', 'support'] },
  ],
  testAssignmentStatus: [
    { value: 'Under Review', keywords: ['under review', 'review'] },
    { value: 'Submitted', keywords: ['submitted', 'submission done'] },
    { value: 'In Progress', keywords: ['in progress', 'doing', 'working'] },
    { value: 'Completed', keywords: ['completed', 'finished', 'done'] },
    { value: 'Not Started', keywords: ['not started', 'todo', 'pending'] },
  ],
  testAssignmentSubmissionFormat: [
    { value: 'Repository + Live Demo', keywords: ['repository + live demo', 'repo and demo'] },
    { value: 'Repository', keywords: ['repository', 'repo'] },
    { value: 'Archive (.zip)', keywords: ['zip', 'archive'] },
    { value: 'Document / Slides', keywords: ['document', 'slides', 'presentation'] },
    { value: 'Other', keywords: ['other'] },
  ],
  leadStatus: [
    { value: 'Negotiation', keywords: ['negotiation', 'negotiating'] },
    { value: 'Proposal', keywords: ['proposal', 'estimation sent'] },
    { value: 'Qualified', keywords: ['qualified', 'qualification'] },
    { value: 'Won', keywords: ['won', 'approved', 'accepted'] },
    { value: 'Lost', keywords: ['lost', 'rejected', 'declined'] },
    { value: 'New', keywords: ['new', 'incoming', 'initial'] },
  ],
  leadSource: [
    { value: 'Referral', keywords: ['referral', 'referred'] },
    { value: 'Upwork', keywords: ['upwork'] },
    { value: 'LinkedIn', keywords: ['linkedin'] },
    { value: 'Website', keywords: ['website', 'site form', 'contact form'] },
    { value: 'Cold Outreach', keywords: ['cold outreach', 'cold email', 'outreach'] },
    { value: 'Other', keywords: ['other'] },
  ],
  apiType: [
    { value: 'GraphQL', keywords: ['graphql'] },
    { value: 'tRPC', keywords: ['trpc', 't-rpc'] },
    { value: 'RPC', keywords: ['rpc'] },
    { value: 'Mixed', keywords: ['mixed'] },
    { value: 'REST', keywords: ['rest'] },
  ],
  wpAcfUsed: [
    { value: 'Yes', keywords: ['yes', 'used'] },
    { value: 'No', keywords: ['no', 'not used'] },
  ],
  wpWooCommerce: [
    { value: 'Yes', keywords: ['yes', 'woocommerce', 'woo'] },
    { value: 'No', keywords: ['no', 'not used'] },
  ],
};

export const SECTION_ICONS: Record<string, string> = {
  'lead-header': '🧲',
  'lead-brief': '🗒️',
  'passport-header': '🪪',
  'project-intent': '🎯',
  'test-assignment-template': '🧪',
  'technical-profile': '🧱',
  'repositories-environments': '🔗',
  'delivery-runbook': '🧭',
  'lead-files': '📎',
  'project-files': '📎',
  'stack-wordpress': '🟦',
  'stack-react': '⚛️',
  'stack-nextjs': '▲',
  'stack-react-native': '📱',
  'stack-electron': '💻',
  'stack-generic-fullstack': '🧩',
  'hosting-vercel': '▲',
  'hosting-netlify': '🟩',
  'hosting-cpanel': '🧰',
  'hosting-shared-hosting': '🗂️',
  'hosting-vps': '🖧',
  'hosting-aws': '☁️',
  'hosting-firebase': '🔥',
  'hosting-render': '🚀',
  'hosting-railway': '🚉',
  'hosting-expo-eas': '📦',
  'hosting-app-store-play-store': '🏪',
  'hosting-desktop-distribution': '🧷',
};

export const FIELD_ICON_BY_ID: Record<string, string> = {
  projectName: '📌',
  passportTemplate: '🧩',
  leadName: '🎯',
  leadContactPerson: '👤',
  communicationChannel: '☎️',
  leadSource: '📥',
  leadStatus: '🟠',
  leadBudget: '💰',
  leadSummary: '📝',
  leadQualificationNotes: '📋',
  leadNextStep: '➡️',
  communicatorPeople: '💬',
  responsiblePeople: '🧑‍💼',
  leadLossReason: '❗',
  client: '🤝',
  department: '🏢',
  designTool: '🎨',
  designToolUrl: '🔗',
  status: '📍',
  projectType: '🗃️',
  priority: '⚡',
  startedAt: '🗓️',
  lastUpdated: '⏱️',
  businessGoal: '🎯',
  scopeIn: '✅',
  scopeOut: '🚫',
  definitionOfDone: '🏁',
  acceptanceCriteria: '📋',
  testAssignmentTitle: '🧾',
  testAssignmentSourceUrl: '🔗',
  testAssignmentStatus: '🚦',
  testAssignmentEstimate: '⏱️',
  testAssignmentSubmissionFormat: '📦',
  testAssignmentDeliverables: '📂',
  testAssignmentEvaluationCriteria: '🧮',
  testAssignmentConstraints: '📏',
  mainStack: '🧱',
  secondaryStack: '🧰',
  platform: '🖥️',
  hostingDeployment: '☁️',
  database: '🗄️',
  cms: '📰',
  authStrategy: '🔐',
  storage: '🧺',
  apiType: '🛰️',
  integrations: '🧬',
  repositoryUrl: '🧾',
  stagingUrl: '🧪',
  productionUrl: '🌍',
  adminUrl: '🛡️',
  apiBaseUrl: '🔌',
  docsUrl: '📚',
  runInstallCommand: '⬇️',
  runStartCommand: '▶️',
  runTestCommand: '🧪',
  runBuildCommand: '🏗️',
  secretStorageReference: '🔐',
  vaultLink: '🗝️',
};
