name: CI Security

on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run SAST
        run: semgrep scan --config auto --error --exclude '.github/workflows/**' .

  sca:
    name: SCA - Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SCA
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'

  secrets:
    name: Secrets Scan - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  secret-injection:
    name: Secret Injection Test
    runs-on: ubuntu-latest

    steps:
      - name: Check injected secret
        env:
          DEMO_API_TOKEN: ${{ secrets.DEMO_API_TOKEN }}
        run: |
          if [ -z "$DEMO_API_TOKEN" ]; then
            echo "Secret is missing"
            exit 1
          fi

          echo "Secret injected successfully"

  aws-secret-test:
    name: AWS OIDC + Secrets Manager
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::658606185886:role/GitHubActionsReadDemoSecret
          aws-region: eu-north-1

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Read secret from Secrets Manager
        run: |
          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id dev/demo/api-token \
            --query SecretString \
            --output text)

          if [ -z "$SECRET" ]; then
            echo "Secret is missing"
            exit 1
          fi

          echo "AWS secret retrieved successfully"
