name: CI Security

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run SAST
        run: semgrep scan --config auto --error --exclude '.github/workflows/**' .

  sca:
    name: SCA - Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SCA
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'

  secrets:
    name: Secrets Scan - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
